version: '3.1'

services:
    mysql:
        image: mysql
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: snakedumper
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - 3306:3306
